import Navbar from "../Components/Navbar/Navbar.jsx";
import "./globals.css";
import Footer from "../Components/Footer/Footer.jsx";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1366px] min-h-[100vh] md:mx-auto py-0 flex-col justify-between">
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
